name: Node.js CI

on:
  schedule:
    - cron: '0 13,14,15,22 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: ROWSERSTACK_ACCESS_KEY=$BROWSERSTACK_ACCESS_KEY
    - run: BROWSERSTACK_USERNAME=$BROWSERSTACK_USERNAME
    - run: |
        npm run test:ex | tee view.html
    - name: Upload math result for job 1
      uses: actions/upload-artifact@v1
      with:
        name: view
        path: view.html
      env:
        CI: true
        BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
        BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
